### PR TITLE
Add new field to CaddyFile field list

### PR DESCRIPTION
**Pull request by moschlar**
This builds on and fixes the initial approach from https://github.com/glatzert/go-authcrunch/commit/8de8c6b3551f74243df07c1f6d083a88974cbb14 to add a new configuration directive to specify the name of the "roles" claim.

Requires https://github.com/greenpau/go-authcrunch/pull/42

### CODE REVIEW

**Comment by greenpau** [comment]
@moschlar , this PR requires CLA.

**Comment by moschlar** [comment]
Done.

**Comment by greenpau** [comment]
@moschlar , thank you for the contribution!

It would be nice if you contribute to https://github.com/authp/authp.github.io and describe the feature.

**Comment by greenpau** [comment]
@moschlar , also, please add a test for the above. Looks like it should be in `caddyfile_identity_store_test.go`.

**Pull request merged**
