### PR TITLE
Fix setting meta UI title

### PR DESCRIPTION
**Pull request by freddyheppell**
Fixed assignment of the title to the author property

### CODE REVIEW

**Comment by greenpau** [comment]
@freddyheppell , thank you for your contribution! Will merge it next week.

**Comment by freddyheppell** [comment]
@greenpau any update on merging this?

**Comment by greenpau** [comment]
@freddyheppell , this weekend! 😄

**Comment by greenpau** [comment]
@freddyheppell , thank you for contributing! 👍 I will release at the end of this weekend.

**Pull request merged**
